[package]
name = "ray_tracer_challenge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.17.3"
rayon = "1.10.0"
uuid = {version = "1.3.1", features = ["v4"]}
